"""Fix Course is_active spelling mistake

Revision ID: 0cb26fdef31d
Revises: 1c56ffb652a8
Create Date: 2025-09-09 21:57:28.680901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0cb26fdef31d'
down_revision: Union[str, Sequence[str], None] = '1c56ffb652a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('courses', 'is_actice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_actice', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('courses', 'is_active')
    # ### end Alembic commands ###
