"""Modify Course model

Revision ID: 1c56ffb652a8
Revises: ad6682b51ede
Create Date: 2025-09-09 21:55:12.416033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c56ffb652a8'
down_revision: Union[str, Sequence[str], None] = 'ad6682b51ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('code', sa.String(length=100), nullable=True))
    op.add_column('courses', sa.Column('course_type', sa.Enum('ONLINE', 'PHYSICAL', name='coursetype'), nullable=True))
    op.add_column('courses', sa.Column('grade', sa.Enum('GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', 'GRADE_10', 'GRADE_11', name='gradetype'), nullable=True))
    op.add_column('courses', sa.Column('batch', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('is_actice', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('fee', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'courses', ['batch'])
    op.create_unique_constraint(None, 'courses', ['code'])
    op.create_foreign_key(None, 'courses', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'teacher_id')
    op.drop_column('courses', 'fee')
    op.drop_column('courses', 'is_actice')
    op.drop_column('courses', 'batch')
    op.drop_column('courses', 'grade')
    op.drop_column('courses', 'course_type')
    op.drop_column('courses', 'code')
    # ### end Alembic commands ###
