"""Create Event, Guardian, Hall models

Revision ID: 681d2100fc97
Revises: 8dd3fc40d4ed
Create Date: 2025-09-09 22:23:39.973303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681d2100fc97'
down_revision: Union[str, Sequence[str], None] = '8dd3fc40d4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
