"""Add Subject relationship to Course

Revision ID: 8dd3fc40d4ed
Revises: 0cb26fdef31d
Create Date: 2025-09-09 21:58:54.881410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd3fc40d4ed'
down_revision: Union[str, Sequence[str], None] = '0cb26fdef31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'subject_id')
    # ### end Alembic commands ###
