"""Add code field to Subject

Revision ID: ad6682b51ede
Revises: de799d7ad753
Create Date: 2025-09-09 18:00:58.790226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6682b51ede'
down_revision: Union[str, Sequence[str], None] = 'de799d7ad753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('code', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'subjects', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_column('subjects', 'code')
    # ### end Alembic commands ###
